#version: "3"
#services:
#  mysql-docker:
#    image: mysql:8.0.34
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: rdstest # database env 이름
#      MYSQL_USER: admin # DB user이름
#      MYSQL_ROOT_PASSWORD: test1234 # root pwad
#      MYSQL_PASSWORD: 1234 # DB pw
#    container_name: "aws-mysql"




version: "3"

services:
  mysql-docker:
    image: mysql:8.0.34
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rdstest
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_PASSWORD: 1234
    container_name: "aws-mysql"
    networks:
      - aws-network
    volumes:
      - mysql-volume:/var/lib/mysql
  aws-server:
    container_name: aws-server
    ports:
      - "8080:8080"
    image: aws-server
    volumes:
      - aws-volume:/var/log
    networks:
      - aws-network
    depends_on: mysql-docker
    environment:
      - DATABASE_URL=jdbc:mysql://mysql-docker:3306/rdstest
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=1234
networks:
  aws-network:
    driver: bridge

volumes:
  mysql-volume:
    driver: local
  aws-volume:
    driver: local

