#version: "3"
#services:
#  mysql-docker:
#    image: mysql:8.0.34
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: rdstest # database env 이름
#      MYSQL_USER: admin # DB user이름
#      MYSQL_ROOT_PASSWORD: test1234 # root pwad
#      MYSQL_PASSWORD: 1234 # DB pw
#    container_name: "aws-mysql"


version: '3'

services:
  mysql-db:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: rdsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
#    healthcheck:
#      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
#      timeout: 20s
#      retries: 10

#  spring-boot-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql-db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db-1:3306/rdsdb
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: 1234

#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - spring-boot-app






