spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: test1234
    username: admin
#    url: jdbc:mysql://localhost:3306/rdstest
    url: jdbc:mysql://aws-mysql:3306/rdstest



