spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    username: admin
#    url: jdbc:mysql://localhost:3306/rdstest
    url: jdbc:mysql://mysql-db-1:3306/rdsdb
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5



